on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build, push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
 
    - name: Build container image
      run: docker build  -t blog-latest -f Dockerfile . 
  
    - name: Docker Login      
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Tag image
      run:  docker tag blog-latest eduardoao/blog-latest    

    - name: Push image to Docker Hub
      run: docker push eduardoao/blog-latest
    
    - name: List image
      run: docker images
  
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login   
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo chmod 666 /var/run/docker.sock
          
          docker stop  blog-latest
          docker rmi -f blog-latest

          docker rm eduardoao/blog-latest:latest
          
          docker pull eduardoao/blog-latest          
          
          docker run -d -p 3000:3000 --name blog-latest -t eduardoao/blog-latest         
          docker ps
    

    
