name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server       
    - uses: actions/download-artifact@v2
      with:
          name: build
          path: build
    - name: Create SSH key
      run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.HOST }}" > ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -rav --delete build/ user@host:/
